---
title: "Homework 1"
subtitle: "WCM Modern Methods for Causal Inference"
date: "Due on Canvas on May 18, 2020 by 3:00pm"
output: 
  wcmtheme::wcm_html: 
    toc: true
    toc_float: true
    number_toc: true
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Please clearly label all questions with the appropriate numbers/letters, and `echo` all relevant `R` code and output. You can alternatively use the `code_folding: hide` option in your YAML. You are encouraged to use the Discussion board on Canvas to discuss this homework.

# Background Story 

Suppose we are interested in assessing the causal effect of ready-to-use therapeutic food (RUTF) on recovery from undernutrition in children in a resource-limited country. RUTF is peanut butter-type paste, fortified with milk proteins and essential nutrients, and does not require water for use (WHO, 2007). Together with some experts in childhood nutrition, we've decided to propose a study to contrast the effect of RUTF with another standard supplement. The outcome of interest is weight gain over two months, and the population of interest is school-aged children.

Suppose we only have two pre-intervention covariates. Specifically, $W_1$ is an indicator equaling 1 if the child has access to potable water.  Likewise, $W_2$ is an indicator equaling 1 if the child suffered from an infectious disease within the two weeks prior to the study initiation. The intervention $A$ is also an indicator equaling 1 if the child received RUTF and 0 if the child received the standard supplement. Finally, the outcome $Y$ represents the child's weight gain in pounds at the study termination.

The above study can be translated into the following structural causal model (SCM): 

- Endogenous nodes: $X=(W_1, W_2, A, Y)$

- Background (exogenous) variables: $U=(U_{W_1},U_{W_2},U_{A},U_{Y})$

- Structural equations $F$: 

\begin{align*}
W_1 & \leftarrow f_{W_1}(U_{W_1})\\
W_2 & \leftarrow f_{W_2}(W_1, U_{W_2})\\
A & \leftarrow f_A(W_1, W_2, U_A)\\
Y & \leftarrow f_{Y}(W_1,W_2, A, U_{Y})
\end{align*}


We will now follow the steps of the causal inference roadmap outlined in Lecture 1.

## Steps 1-2 of the Roadmap

**Step 1: Causal model representing real knowledge**

1. Draw the accompanying directed acyclic graph (DAG).

2. Are there any exclusion restrictions or independence assumptions?

**Step 2: Counterfactuals \& causal parameter**

3. Define the counterfactual outcomes of interest with formal notation and in words.

4. How are counterfactuals derived?

5. Suppose we are interested in the average treatment effect. Specify the target causal parameter. Use formal notation and then explain in words.


# A specific data generating process

Now we will consider a particular data generating process, one of many
compatible with the SCM.  Suppose that the each of the background
factors is drawn independently from following
distributions: 

$$
\begin{aligned}
U_{W_1} & \sim \mathrm{Uniform(0,1)}\\
U_{W_2} & \sim \mathrm{Uniform(0,1)}\\
U_A & \sim \mathrm{Uniform(0,1)}\\
U_Y & \sim \mathrm{Normal(\mu=0, \sigma^2 = 0.3^2)}\\
\end{aligned}
$$

Given the background $U$, the endogenous variables are deterministically generated as:

$$
\begin{aligned}
W_1 & \leftarrow \mathrm{I}[U_{W_1}<0.2]\\
W_2& \leftarrow \mathrm{I}[U_{W_2}< \mathrm{expit(0.5\times W_1)}]\\
A &\leftarrow \mathrm{I}[U_A<\mathrm{expit(W_1\times W_2)}]\\
Y &\leftarrow 4\times A + 0.7\times W_1 - 2\times A\times W_2+U_Y
\end{aligned}
$$

where $\mathrm{I}(X)$ is the indicator function taking the value 1 if the condition $X$ is true and 0 if it is false: \[ \mathrm{expit(x)} = \frac{\exp(x)}{1+\exp(x)} \]

Recall from Lab 2 that the $expit$ function is the inverse of the $logit$ function and is given by the `plogis` function in `R`.

## Closed form evaluation of the target causal parameter 

**6. Evaluate the target causal parameter $\theta^*$ in closed form (i.e. by hand) for this data generating process.** 

*Hints:* In this particular data generating system (one of many compatible with the SCM), the expectation of the counterfactual outcome is a linear function of the treatment level $a$, the pre-intervention covariates $(W_1,W_2)$ and random error $U_Y$: \[
E^*(Y_a) = E^* \big[ 4\times a + 0.7\times W_1 - 2\times a\times W_2+U_Y \big], \] where you should note that the expectation is with respect to the distribution of $(W_1,W_2,U_Y)$, not including $A$, since $A=a$ is fixed (i.e., not random) in the counterfactual world. The marginal distribution of $W_1$ (access to potable water) is Bernoulli with probability 0.20:\[ P^*(W_1=1) = E^*(W_1) = 0.20 \] The conditional expectation of $W_2$  (presence or absence of an infectious disease), given $W_1$,  is given by \[ P^*(W_2=1 || W_1) =E^*(W_2|W_1) =  \mathrm{expit}(0.5 \times W_1) \]

**7. Translate this data generating process for $\mathsf{P}^*$ into simulations.**

  a. **First set the seed to 252.**

  b. **Set `n=50,000` as the number of i.i.d. draws from the data generating process.**

  c. **Simulate the background factors $U$.** 

  d. **Evaluate the structural equations $F$ to deterministically generate the endogenous nodes $X$.** Recall the $expit$ function is given by the `plogis` function in `R`.

  e. **Intervene to set the supplement to RUTF ($A=1$) and generate counterfactual outcomes $Y_1$ for $n$ units. Then intervene to set the supplement to the standard ($A=0$) and generate counterfactual outcomes $Y_0$ for $n$ units.**

  f. **Create a data frame to hold the values of the endogenous factors $(W_1,W_2,A,Y)$ and the counterfactual outcomes $Y_1$ and $Y_0$. The rows are the $n$ children and the columns are their characteristics. Use the `head` and `summary` to examine the resulting data.**
  
**8. Evaluate the causal parameter $\theta^*$ for this population of 50,000 units.**

**9. Interpret $\theta^*$.**


## Defining the target causal parameter with a working MSM

Now suppose we are interested in knowing if age in years $V$ modifies the effect of RUTF $A$ on weight gain $Y$. As before, $W_1$ is an indicator of access to potable water and $W_2$ is an indicator of having an infectious disease within two weeks of the study initiation.

Consider the following  SCM:

- Endogenous nodes: $X = (V, W_1,  W_2, A, Y)$
- Exogenous nodes: $U = (U_V, U_{W_1}, U_{W_2}, U_A, U_Y) \sim \mathrm{P}^*$
-  Structural equations $F$:
$$
\begin{aligned}
V & \leftarrow f_{V}(U_V)\\
Y & \leftarrow f_{Y}(V, W_1,W_2, A, U_{Y})
\end{aligned}
$$
- We have made an exclusion restriction that age $V$ does not effect access to potable water $W_1$.

Let us summarize how the counterfactual outcome changes as a function of the intervention and age with the following *working* marginal structural model (MSM):

\begin{align*}
\beta^* &= \arg\min_{\beta} \ \mathsf{E}^*\left[ \sum_{a\in \mathcal{A}} \big(Y_a - m(a, V | \beta)\big)^2 \right] \\
m(a, V |\beta) &= \beta_0 + \beta_1 a + \beta_2 V + \beta_3 a\times V
\end{align*}

Then the target parameter is defined as a projection of the true causal curve $\mathsf{E}^*(Y_a |V)$ onto a working model $m(a,V|\beta)$. In other words, the causal parameters are the values of the $\beta$ coefficients that minimize the sum of squared residuals between the counterfactuals $Y_a$ and the model $m(a, V | \beta)$ for all possible exposure levels $a \in \mathcal{A}$.

Based on our knowledge of the data generating system, as represented in the SCM, a linear working MSM with an interaction term may or may not be a good summary of how the effect of RUTF on the counterfactual average weight gain is modified by age.

## A specific data generating process:

Consider a new data generating process (one of many compatible with the  SCM). Suppose that the each of the  exogenous factors is drawn independently from following distributions:
$$
\begin{aligned}
U_{V} & \sim \mathrm{Uniform(0, 3)} \\
U_{W_1} & \sim \mathrm{Uniform(0,1)}\\
U_{W_2} & \sim \mathrm{Uniform(0,1)}\\
U_A & \sim \mathrm{Uniform(0,1)}\\
U_Y & \sim \mathrm{Normal(\mu=0, \sigma^2 = 0.1^2)}
\end{aligned}
$$
Given the exogenous $U$, the endogenous variables $X$ are deterministically generated as
$$
\begin{aligned}
V & \leftarrow 2+ U_V\\
W_1 & \leftarrow \mathrm{I}[U_{W_1}<0.2]\\
W_2 & \leftarrow \mathrm{I}[U_{W_2}<\mathrm{expit}(0.5^*W_1)]\\
A & \leftarrow \mathrm{I}[U_A<\mathrm{expit}(W_1^*W_2 + V/5)]\\
Y & \leftarrow 4^*A + 0.7^*W_1 - 2^*A^*W_2 + .3^*V -.3^*A^*V + U_Y
\end{aligned}
$$

**10. For $n=5,000$ children, generate the exogenous factors $U$ and the pre-intervention covariates $(V, W_1,W_2)$. Then set $A=1$ to generate the counterfactual weight gain under RUTF $Y_1$. Likewise, set $A=0$ to generate the counterfactual weight gain under the standard supplement $Y_0$.**

**11. Create a data frame `X_msm`  consisting of age $V$, the set treatment levels $a$, and the corresponding outcomes $Y_a$.**

$$ X_{MSM} = (V,a,Y_a) = \left( \begin{array}{ccc}
V(1) & 1 & Y_1(1) \\
V(2) & 1 & Y_1(2) \\
\vdots & \vdots & \vdots \\
V(n) & 1 & Y_1(n) \\
V(1) & 0 & Y_0(1) \\
V(2) & 0 & Y_0(2) \\
\vdots & \vdots & \vdots \\
V(n) & 0 & Y_0(n)
\end{array} \right) $$


where $V(i)$ and $Y_a(i)$ denote the age and counterfactual outcome for the $i^{th}$ subject. See `R` lab 1 for a similar example.

**12. Evaluate the target causal parameter.** We have defined the target parameter using the least square projection (i.e. with the L2 loss function). Use the `glm` function to fit the coefficients of the working MSM. Specifically, regress the counterfactual outcomes $Y_a$ on $a$ and $V$ according to the working MSM. Be sure to specify the argument: `data=X_msm`.

**13. Plot of the counterfactual outcomes $Y_a$ as a function of age ($V$) and treatment group ($a$).**

**14. Interpret the results.**


